DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT (
    ID IDENTITY NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    AGE INT NOT NULL,
    TEL VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    GENDER BOOLEAN NOT NULL,
    SCHOOLS VARCHAR(255) NOT NULL
);