DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT (
    id IDENTITY NOT NULL PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    user_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    address VARCHAR(255) NOT NULL,
    gender  BOOLEAN NOT NULL,
    tel VARCHAR(255) NOT NULL,
    schools VARCHAR(255) NOT NULL
);